### ISSUE TITLE
Killing terminal of one kak instance results in other clients dying

### ISSUE THREAD

**Issue by Doix** [mawww/kakoune#1552]
If I have two kak clients running in two separate terminal emulators and I kill one of the terminal emulators, the other kak client dies. 

This gets printed in the terminal: 
terminate called after throwing an instance of 'Kakoune::disconnected'

If I exist kak cleanly (say with :q) then everything works correctly.

Built off main branch, at commit 8cef1932a00dc1bcfd8af829a829e979b835ccfb

**Comment by lenormf** [comment]
Stacktrace:

```
#0  0x00007f72f7be9bf0 in __write_nocancel () from /usr/lib/libc.so.6
#1  0x0000555555b7b4e7 in Kakoune::send_data (fd=4, buffer=std::vector of length 9, capacity 486 = {...}) at remote.cc:371
#2  0x0000555555b7bbb6 in Kakoune::RemoteUI::~RemoteUI (this=0x55555654b0d0, __in_chrg=<optimized out>) at remote.cc:422
#3  0x0000555555b7bcc8 in Kakoune::RemoteUI::~RemoteUI (this=0x55555654b0d0, __in_chrg=<optimized out>) at remote.cc:426
#4  0x000055555593a310 in std::default_delete<Kakoune::UserInterface>::operator() (this=0x55555654aa50, __ptr=0x55555654b0d0) at /usr/include/c++/7.1.1/bits/unique_ptr.h:78
#5  0x00005555559387f1 in std::unique_ptr<Kakoune::UserInterface, std::default_delete<Kakoune::UserInterface> >::~unique_ptr (this=0x55555654aa50, __in_chrg=<optimized out>) at /usr/include/c++/7.1.1/bits/unique_ptr.h:268
#6  0x000055555593295a in Kakoune::Client::~Client (this=0x55555654aa40, __in_chrg=<optimized out>) at client.cc:59
#7  0x000055555594924e in std::default_delete<Kakoune::Client>::operator() (this=0x55555654a9a0, __ptr=0x55555654aa40) at /usr/include/c++/7.1.1/bits/unique_ptr.h:78
#8  0x00005555559483c7 in std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> >::~unique_ptr (this=0x55555654a9a0, __in_chrg=<optimized out>) at /usr/include/c++/7.1.1/bits/unique_ptr.h:268
#9  0x0000555555947132 in std::allocator_traits<Kakoune::Allocator<std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> >, (Kakoune::MemoryDomain)16> >::_S_destroy<Kakoune::Allocator<std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> >, (Kakoune::MemoryDomain)16>, std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> > > (__p=0x55555654a9a0) at /usr/include/c++/7.1.1/bits/alloc_traits.h:261
#10 0x0000555555945964 in std::allocator_traits<Kakoune::Allocator<std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> >, (Kakoune::MemoryDomain)16> >::destroy<std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> > > (__a=..., __p=0x55555654a9a0) at /usr/include/c++/7.1.1/bits/alloc_traits.h:356
#11 0x00005555559444c4 in std::_Destroy<std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> >*, Kakoune::Allocator<std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> >, (Kakoune::MemoryDomain)16> > (__first=0x55555654a9a0, __last=0x55555654a9a8, __alloc=...) at /usr/include/c++/7.1.1/bits/stl_construct.h:188
#12 0x00005555559446ea in std::vector<std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> >, Kakoune::Allocator<std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> >, (Kakoune::MemoryDomain)16> >::_M_erase_at_end (this=0x7fffffffd7a8, __pos=0x55555654a9a0) at /usr/include/c++/7.1.1/bits/stl_vector.h:1513
#13 0x0000555555943616 in std::vector<std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> >, Kakoune::Allocator<std::unique_ptr<Kakoune::Client, std::default_delete<Kakoune::Client> >, (Kakoune::MemoryDomain)16> >::clear (this=0x7fffffffd7a8) at /usr/include/c++/7.1.1/bits/stl_vector.h:1248
#14 0x0000555555941a94 in Kakoune::ClientManager::clear_client_trash (this=0x7fffffffd790) at client_manager.cc:166
#15 0x0000555555abc3fe in Kakoune::run_server (session=..., server_init=..., client_init=..., init_coord=..., flags=Kakoune::ServerFlags::StartupInfo, ui_type=Kakoune::UIType::NCurses, files=...) at main.cc:640
#16 0x0000555555ac023e in main (argc=1, argv=0x7fffffffe6e8) at main.cc:958
```
