### ISSUE TITLE
Infinite loop when opening a doc page

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#1661]
Hi,

It seems like an infinite loop is triggered when the current buffer is a documentation page.

On two occasions, I used `:doc commands`, then while scrolling around ended up triggering the loop which yielded the following two stacktraces, when the process was broken into with `gdb`:

```
#0  Kakoune::RefPtr<Kakoune::StringData, Kakoune::StringData::PtrPolicy>::operator-> (this=0x557e7acfcf40) at ref_ptr.hh:72
#1  Kakoune::Buffer::LineList::operator[] (line=..., this=0x557e7aac9860) at buffer.hh:243
#2  Kakoune::Buffer::operator[] (this=0x557e7aac96c0, line=...) at buffer.hh:172
#3  0x0000557e79878dce in Kakoune::get_byte_to_column (buffer=..., tabstop=..., coord=...) at buffer_utils.cc:38
#4  0x0000557e799565d3 in Kakoune::WrapHighlighter::next_split_coord (this=0x557e7acfaff0, buffer=..., wrap_column=..., tabstop=4, coord=...) at highlighters.cc:828
#5  0x0000557e79955bb1 in Kakoune::WrapHighlighter::do_compute_display_setup (this=0x557e7acfaff0, context=..., setup=...) at highlighters.cc:786
#6  0x0000557e7993cbe5 in Kakoune::Highlighter::compute_display_setup (this=0x557e7acfaff0, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter.hh:68
#7  0x0000557e7993b2ab in Kakoune::HighlighterGroup::do_compute_display_setup (this=0x557e7aac9820, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter_group.cc:19
#8  0x0000557e7993cbe5 in Kakoune::Highlighter::compute_display_setup (this=0x557e7aac9820, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter.hh:68
#9  0x0000557e7993c1c7 in Kakoune::Highlighters::compute_display_setup (this=0x557e7aac9810, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter_group.cc:84
#10 0x0000557e7993c1ac in Kakoune::Highlighters::compute_display_setup (this=0x557e7aaef580, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter_group.cc:83
#11 0x0000557e7993c1ac in Kakoune::Highlighters::compute_display_setup (this=0x557e7aaef620, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter_group.cc:83
#12 0x0000557e79af400c in Kakoune::Window::compute_display_setup (this=0x557e7aaef430, context=...) at window.cc:203
#13 0x0000557e79af2b63 in Kakoune::Window::update_display_buffer (this=0x557e7aaef430, context=...) at window.cc:122
#14 0x0000557e79880ef6 in Kakoune::Client::redraw_ifn (this=0x557e7aa63e40) at client.cc:217
#15 0x0000557e7988e142 in Kakoune::ClientManager::redraw_clients (this=0x7fff82960220) at client_manager.cc:194
#16 0x0000557e799eb1a6 in Kakoune::run_server (session=..., server_init=..., client_init=..., init_coord=..., flags=Kakoune::ServerFlags::StartupInfo, ui_type=Kakoune::UIType::NCurses, files=...) at main.cc:654
#17 0x0000557e799ef06d in main (argc=1, argv=0x7fff829611b8) at main.cc:982
```

```
#0  0x0000560796404910 in Kakoune::StringView::StringView (this=0x560796fda340, data=0x9 <error: Cannot access memory at address 0x9>, length=...) at string.hh:215
#1  0x000056079640ccf9 in Kakoune::StringData::strview (this=0x560797141a80) at shared_string.hh:22
#2  Kakoune::Buffer::LineList::operator[] (line=..., this=0x560796fda340) at buffer.hh:243
#3  Kakoune::Buffer::char_next (this=0x560796fda1a0, coord=...) at buffer.cc:644
#4  0x000056079650461f in Kakoune::WrapHighlighter::next_split_coord (this=0x5607971e2ab0, buffer=..., wrap_column=..., tabstop=4, coord=...) at highlighters.cc:830
#5  0x0000560796503bb1 in Kakoune::WrapHighlighter::do_compute_display_setup (this=0x5607971e2ab0, context=..., setup=...) at highlighters.cc:786
#6  0x00005607964eabe5 in Kakoune::Highlighter::compute_display_setup (this=0x5607971e2ab0, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter.hh:68
#7  0x00005607964e92ab in Kakoune::HighlighterGroup::do_compute_display_setup (this=0x560796fda300, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter_group.cc:19
#8  0x00005607964eabe5 in Kakoune::Highlighter::compute_display_setup (this=0x560796fda300, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter.hh:68
#9  0x00005607964ea1c7 in Kakoune::Highlighters::compute_display_setup (this=0x560796fda2f0, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter_group.cc:84
#10 0x00005607964ea1ac in Kakoune::Highlighters::compute_display_setup (this=0x5607971a8cb0, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter_group.cc:83
#11 0x00005607964ea1ac in Kakoune::Highlighters::compute_display_setup (this=0x5607971a8d50, context=..., pass=Kakoune::HighlightPass::Wrap, setup=...) at highlighter_group.cc:83
#12 0x00005607966a200c in Kakoune::Window::compute_display_setup (this=0x5607971a8b60, context=...) at window.cc:203
#13 0x00005607966a0b63 in Kakoune::Window::update_display_buffer (this=0x5607971a8b60, context=...) at window.cc:122
#14 0x000056079642eef6 in Kakoune::Client::redraw_ifn (this=0x560796ee1e50) at client.cc:217
#15 0x000056079643c142 in Kakoune::ClientManager::redraw_clients (this=0x7ffe975ee910) at client_manager.cc:194
#16 0x00005607965991a6 in Kakoune::run_server (session=..., server_init=..., client_init=..., init_coord=..., flags=Kakoune::ServerFlags::None, ui_type=Kakoune::UIType::NCurses, files=...) at main.cc:654
#17 0x000056079659d06d in main (argc=2, argv=0x7ffe975ef8a8) at main.cc:982
```

HTH.

**Comment by mawww** [comment]
That is due to having multiple wrap highlighters running, which is an unfortunate side effect of moving highlighters to scopes. I am not sure yet how to fix that, multiple options come to mind but none are entirely satisfying.

**Comment by mawww** [comment]
The infinite loop is fixed, rendering is still strange if multiple wrap highlighters are fighting.

**Comment by lenormf** [comment]
Closing this in favor of #1668.
