### ISSUE TITLE
[bug] Assert failed "it != m_handler.m_mode_stack.end()" at input_handler.cc:1618

### ISSUE THREAD

**Issue by sasdf** [mawww/kakoune#2551]
### Steps
Minimal kakrc:
```
declare-user-mode bufs
map global bufs 1 ':buffer b<ret>:enter-user-mode -lock bufs<ret>' -docstring 'b'
map global bufs 2 ':buffer a<ret>:enter-user-mode -lock bufs<ret>' -docstring 'a'
map global normal -- '-' ':enter-user-mode -lock bufs<ret>'
```
Commandline:
```
kak a b
```
Keystrokes:
```
-12
```
Tested on alpine 3.8 with musl libc and ncurses 6.1.

### Outcome
```
assert failed "it != m_handler.m_mode_stack.end()" at input_handler.cc:1618
```

### Expected
It shouldn't crash.

**Comment by mawww** [comment]
Hello,

I cannot reproduce here on latest git, do that happen on a specific version ? What does `:echo %val{version}` display ?

**Comment by lenormf** [comment]
I could reproduce it in `alpine` as well, on the development version.

**Comment by lenormf** [comment]
```
#0  Kakoune::on_assert_failed (message=0x7ffff7cba548 "assert failed \"it != m_handler.m_mode_stack.end()\" at input_handler.cc:1618") at assert.cc:43
#1  0x00007ffff7aa5652 in Kakoune::InputHandler::ScopedForceNormal::~ScopedForceNormal (this=0x7fffffffc820, __in_chrg=<optimized out>) at input_handler.cc:1618
#2  0x00007ffff79b48bb in Kakoune::(anonymous namespace)::<lambda(Kakoune::Key, Kakoune::Context&)>::operator()(Kakoune::Key, Kakoune::Context &) (__closure=0x7ffff83653c8, key=..., context=...) at commands.cc:2280
#3  0x00007ffff79c0a0e in Kakoune::<lambda(Kakoune::Key, Kakoune::Context&)>::operator()(Kakoune::Key, Kakoune::Context &) (__closure=0x7ffff83653c0, key=..., context=...) at input_handler.hh:182
#4  0x00007ffff79caf9a in std::_Function_handler<void(Kakoune::Key, Kakoune::Context&), Kakoune::on_next_key_with_autoinfo(const Kakoune::Context&, Kakoune::KeymapMode, Cmd, Kakoune::StringView, Kakoune::StringView) [with Cmd = Kakoune::(anonymous namespace)::enter_user_mode(Kakoune::Context&, Kakoune::String, Kakoune::KeymapMode, bool)::<lambda(Kakoune::Key, Kakoune::Context&)>]::<lambda(Kakoune::Key, Kakoune::Context&)> >::_M_invoke(const std::_Any_data &, Kakoune::Key &&, Kakoune::Context &) (__functor=..., __args#0=..., __args#1=...) at /usr/include/c++/6.4.0/functional:1731
#5  0x00007ffff7ab9d3f in std::function<void (Kakoune::Key, Kakoune::Context&)>::operator()(Kakoune::Key, Kakoune::Context&) const (this=0x7ffff8364158, __args#0=..., __args#1=...) at /usr/include/c++/6.4.0/functional:2127
#6  0x00007ffff7ab11dd in Kakoune::InputModes::NextKey::on_key (this=0x7ffff8364140, key=...) at input_handler.cc:1101
#7  0x00007ffff7aa7847 in Kakoune::InputMode::handle_key (this=0x7ffff8364140, key=...) at input_handler.cc:32
#8  0x00007ffff7aa57eb in Kakoune::InputHandler::<lambda(Kakoune::Key)>::operator()(Kakoune::Key) const (__closure=0x7fffffffca10, key=...) at input_handler.cc:1643
#9  0x00007ffff7aa59f1 in Kakoune::InputHandler::handle_key (this=0x7ffff8363818, key=...) at input_handler.cc:1655
#10 0x00007ffff796f730 in Kakoune::Client::process_pending_inputs (this=0x7ffff83637a0) at client.cc:98
#11 0x00007ffff797f3f9 in Kakoune::ClientManager::process_pending_inputs (this=0x7fffffffcf60) at client_manager.cc:88
#12 0x00007ffff7b06dc3 in Kakoune::run_server (session="", server_init="", client_init="", init_coord=..., flags=Kakoune::ServerFlags::None, ui_type=Kakoune::UIType::NCurses, debug_flags=Kakoune::DebugFlags::None, files=ArrayView<Kakoune::StringView> = {...}) at main.cc:744
#13 0x00007ffff7b0b02a in main (argc=3, argv=0x7fffffffe6a8) at main.cc:1081
```

**Comment by lenormf** [comment]
Is this still occurring?

**Comment by mawww** [comment]
re-open if reproducible.
