### ISSUE TITLE
[regex_match] Memory leak

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2556]
```
Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x517232 in operator new[](unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/asan/asan_new_delete.cc:95:3                                                                                         
    #1 0x5bfbdc in Kakoune::ThreadedRegexVM<char*, (Kakoune::MatchDirection)0>::DualThreadStack::grow_ifn() /mnt/fuzzers/regex/../../src/regex_impl.hh:650:32                                                      
    #2 0x5bd43b in Kakoune::ThreadedRegexVM<char*, (Kakoune::MatchDirection)0>::exec_program(char*, Kakoune::ThreadedRegexVM<char*, (Kakoune::MatchDirection)0>::ExecConfig const&) /mnt/fuzzers/regex/../../src/regex_impl.hh:467:19
    #3 0x5bb3b2 in Kakoune::ThreadedRegexVM<char*, (Kakoune::MatchDirection)0>::exec(char*, char*, char*, char*, Kakoune::RegexExecFlags) /mnt/fuzzers/regex/../../src/regex_impl.hh:230:16                        
    #4 0x5b96d2 in bool Kakoune::regex_match<char*>(char*, char*, Kakoune::MatchResults<char*>&, Kakoune::Regex const&) /mnt/fuzzers/regex/../../src/regex.hh:123:12                                               
    #5 0x5b906e in LLVMFuzzerTestOneInput /mnt/fuzzers/regex/match_self.cc:15:9
    #6 0x43184c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:515:13                                                  
    #7 0x4310ab in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:440:3                           
    #8 0x432add in fuzzer::Fuzzer::MutateAndTestOne() /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:648:19                                                                                    
    #9 0x433395 in fuzzer::Fuzzer::Loop(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, fuzzer::fuzzer_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:775:5                                                                                                     
    #10 0x4280a0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:754:6                                   
    #11 0x449ca2 in main /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #12 0x7ff272b5c222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)
```

Reproducer:

```
||||
```

Seems to have been introduced by 528ecb74171a227f942de2ddaf80cedb82136740.

**Comment by mawww** [comment]
Stupid mistake, I'll fix that.
