### ISSUE TITLE
Segmentation fault when selecting an argument object

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#2966]
Git HEAD.

### Steps 

* Create a file with an empty line followed by a closing bracket:

```

]
```
* Place the selection on the empty line
* Perform an argument selection with `<a-a>u`

### Outcome 

```
Received SIGSEGV, exiting.
Pid: 14422
Callstack:
kak(Kakoune::Backtrace::Backtrace()+0x19) [0x5635dab937d9]
kak(Kakoune::signal_handler(int)+0x65) [0x5635dac77925]
/usr/lib/libc.so.6(+0x378b0) [0x7f0f7c4898b0]
kak(+0x1fd9bd) [0x5635dad059bd]
kak(Kakoune::select_argument(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)+0x56e) [0x5635dad080be]
kak(void Kakoune::select<(Kakoune::SelectMode)0, std::_Bind<Kakoune::Optional<Kakoune::Selection> (*(std::_Placeholder<1>, std::_Placeholder<2>, int, Kakoune::ObjectFlags))(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)> >(Kakoune::Context&, std::_Bind<Kakoune::Optional<Kakoune::Selection> (*(std::_Placeholder<1>, std::_Placeholder<2>, int, Kakoune::ObjectFlags))(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)>)+0xc6) [0x5635dacb6a26]
kak(void Kakoune::select_and_set_last<(Kakoune::SelectMode)0, std::_Bind<Kakoune::Optional<Kakoune::Selection> (*(std::_Placeholder<1>, std::_Placeholder<2>, int, Kakoune::ObjectFlags))(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)> >(Kakoune::Context&, std::_Bind<Kakoune::Optional<Kakoune::Selection> (*(std::_Placeholder<1>, std::_Placeholder<2>, int, Kakoune::ObjectFlags))(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)>&&)+0xbd) [0x5635dacb6dfd]
kak(Kakoune::select_object<(Kakoune::ObjectFlags)3, (Kakoune::SelectMode)0>(Kakoune::Context&, Kakoune::NormalParams)::{lambda(Kakoune::Key, Kakoune::Context&)#2}::operator()(Kakoune::Key, Kakoune::Context&) const+0x577) [0x5635dacc6f47]
kak(Kakoune::InputModes::NextKey::on_key(Kakoune::Key)+0x5f) [0x5635dac441ef]
kak(Kakoune::InputHandler::handle_key(Kakoune::Key)+0xd8) [0x5635dac41218]
kak(Kakoune::Client::process_pending_inputs()+0x153) [0x5635daba7163]
kak(Kakoune::ClientManager::process_pending_inputs()+0x7a) [0x5635dabadaaa]
kak(Kakoune::run_server(Kakoune::StringView, Kakoune::StringView, Kakoune::StringView, Kakoune::Optional<Kakoune::BufferCoord>, Kakoune::ServerFlags, Kakoune::UIType, Kakoune::DebugFlags, Kakoune::ArrayView<Kakoune::StringView const>)+0xac4) [0x5635dac7ddb4]
kak(main+0x1d1a) [0x5635dab915da]
/usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7f0f7c475ce3]
kak(_start+0x2e) [0x5635dab91d6e]
```

**Comment by nonumeros** [comment]
mine with https://github.com/mawww/kakoune/commit/1ebea85e6f07aeb6a8287b8043480f56f0e58edb

```
Received SIGSEGV, exiting. 
Pid: 16346 
Callstack: 
kak(_ZN7Kakoune9BacktraceC1Ev+0x18) [0x558b920504c8] 
kak(_ZN7Kakoune14signal_handlerEi+0x64) [0x558b92131b84] /usr/lib/libc.so.6(+0x378b0) [0x7fe6e357f8b0] 
kak(+0x1fa5fd) [0x558b921be5fd] 
kak(_ZN7Kakoune15select_argumentERKNS_7ContextERKNS_9SelectionEiNS_11ObjectFlagsE+0x56e) [0x558b921c0cce] kak(_ZN7Kakoune6selectILNS_10SelectModeE0ESt5_BindIFPFNS_8OptionalINS_9SelectionEEERKNS_7ContextERKS4_iNS_11ObjectFlagsEESt12_PlaceholderILi1EESE_ILi2EEiSB_EEEEvRS6_T0_+0xc6) [0x558b9216fbb6] kak(_ZN7Kakoune19select_and_set_lastILNS_10SelectModeE0ESt5_BindIFPFNS_8OptionalINS_9SelectionEEERKNS_7ContextERKS4_iNS_11ObjectFlagsEESt12_PlaceholderILi1EESE_ILi2EEiSB_EEEEvRS6_OT0_+0xbc) [0x558b9216ff7c] kak(_ZZN7Kakoune13select_objectILNS_11ObjectFlagsE3ELNS_10SelectModeE0EEEvRNS_7ContextENS_12NormalParamsEENKUlNS_3KeyES4_E0_clES6_S4_+0x564) [0x558b9217fce4] 
kak(_ZN7Kakoune10InputModes7NextKey6on_keyENS_3KeyE+0x5f) [0x558b920fed2f] 
kak(_ZN7Kakoune12InputHandler10handle_keyENS_3KeyE+0xd6) [0x558b920fbe26] 
kak(_ZN7Kakoune6Client22process_pending_inputsEv+0x150) [0x558b92063b50] 
kak(_ZN7Kakoune13ClientManager22process_pending_inputsEv+0x78) [0x558b9206a308] kak(_ZN7Kakoune10run_serverENS_10StringViewES0_S0_NS_8OptionalINS_11BufferCoordEEENS_11ServerFlagsENS_6UITypeENS_10DebugFlagsENS_9ArrayViewIKS0_EE+0xa8b) [0x558b92137deb] 
kak(main+0x1ce7) [0x558b9204e2f7] 
/usr/lib/libc.so.6(__libc_start_main+0xf3) [0x7fe6e356bce3] 
kak(_start+0x2e) [0x558b9204ea7e]
```

**Comment by lenormf** [comment]
Backtrace:

```
#0  0x000055555597f70c in Kakoune::StringData::strview (this=0x21) at shared_string.hh:22
#1  Kakoune::Buffer::LineList::operator[] (line=-1, this=0x555555f86760) at buffer.hh:252
#2  Kakoune::Buffer::operator[] (this=0x555555f861c0, line=-1) at buffer.hh:180
#3  0x0000555555980d8f in Kakoune::BufferIterator::operator-- (this=0x7fffffffc660) at buffer.inl.hh:206
#4  0x0000555555c46c6c in Kakoune::select_argument (context=..., selection=..., level=0, flags=(Kakoune::ObjectFlags::ToBegin | Kakoune::ObjectFlags::ToEnd)) at selectors.cc:803
#5  0x0000555555bf4980 in std::__invoke_impl<Kakoune::Optional<Kakoune::Selection>, Kakoune::Optional<Kakoune::Selection> (*&)(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags), Kakoune::Context&, Kakoune::Selection&, int&, Kakoune::ObjectFlags&> (__f=@0x7fffffffc9c0: 0x555555c465af <Kakoune::select_argument(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)>, __args#0=..., __args#1=..., __args#2=@0x7fffffffc9cc: 0, __args#3=@0x7fffffffc9c8: (Kakoune::ObjectFlags::ToBegin | Kakoune::ObjectFlags::ToEnd)) at /usr/include/c++/8.3.0/bits/invoke.h:60
#6  0x0000555555bf07ed in std::__invoke<Kakoune::Optional<Kakoune::Selection> (*&)(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags), Kakoune::Context&, Kakoune::Selection&, int&, Kakoune::ObjectFlags&> (__fn=@0x7fffffffc9c0: 0x555555c465af <Kakoune::select_argument(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)>, __args#0=..., __args#1=..., __args#2=@0x7fffffffc9cc: 0, __args#3=@0x7fffffffc9c8: (Kakoune::ObjectFlags::ToBegin | Kakoune::ObjectFlags::ToEnd)) at /usr/include/c++/8.3.0/bits/invoke.h:96
#7  0x0000555555bea447 in std::_Bind<Kakoune::Optional<Kakoune::Selection> (*(std::_Placeholder<1>, std::_Placeholder<2>, int, Kakoune::ObjectFlags))(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)>::__call<Kakoune::Optional<Kakoune::Selection>, Kakoune::Context&, Kakoune::Selection&, 0ul, 1ul, 2ul, 3ul>(std::tuple<Kakoune::Context&, Kakoune::Selection&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (this=0x7fffffffc9c0, __args=...) at /usr/include/c++/8.3.0/functional:402
#8  0x0000555555be1295 in std::_Bind<Kakoune::Optional<Kakoune::Selection> (*(std::_Placeholder<1>, std::_Placeholder<2>, int, Kakoune::ObjectFlags))(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)>::operator()<Kakoune::Context&, Kakoune::Selection&, Kakoune::Optional<Kakoune::Selection> >(Kakoune::Context&, Kakoune::Selection&) (this=0x7fffffffc9c0, __args#0=..., __args#1=...) at /usr/include/c++/8.3.0/functional:484
#9  0x0000555555bd76c2 in Kakoune::select<(Kakoune::SelectMode)0, std::_Bind<Kakoune::Optional<Kakoune::Selection> (*(std::_Placeholder<1>, std::_Placeholder<2>, int, Kakoune::ObjectFlags))(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)> >(Kakoune::Context&, std::_Bind<Kakoune::Optional<Kakoune::Selection> (*(std::_Placeholder<1>, std::_Placeholder<2>, int, Kakoune::ObjectFlags))(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)>) (context=..., func=...) at normal.cc:97
#10 0x0000555555bcc9e3 in Kakoune::select_and_set_last<(Kakoune::SelectMode)0, std::_Bind<Kakoune::Optional<Kakoune::Selection> (*(std::_Placeholder<1>, std::_Placeholder<2>, int, Kakoune::ObjectFlags))(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)> >(Kakoune::Context&, std::_Bind<Kakoune::Optional<Kakoune::Selection> (*(std::_Placeholder<1>, std::_Placeholder<2>, int, Kakoune::ObjectFlags))(Kakoune::Context const&, Kakoune::Selection const&, int, Kakoune::ObjectFlags)>&&) (context=..., func=...) at normal.cc:136
#11 0x0000555555bac390 in Kakoune::select_object<(Kakoune::ObjectFlags)3, (Kakoune::SelectMode)0>(Kakoune::Context&, Kakoune::NormalParams)::{lambda(Kakoune::Key, Kakoune::Context&)#2}::operator()(Kakoune::Key, Kakoune::Context&) const (this=0x555555f8835c, key=..., context=...) at normal.cc:1291
#12 0x0000555555bcd8de in Kakoune::on_next_key_with_autoinfo<Kakoune::select_object<(Kakoune::ObjectFlags)3, (Kakoune::SelectMode)0>(Kakoune::Context&, Kakoune::NormalParams)::{lambda(Kakoune::Key, Kakoune::Context&)#2}>(Kakoune::Context const&, Kakoune::KeymapMode, Kakoune::select_object<(Kakoune::ObjectFlags)3, (Kakoune::SelectMode)0>(Kakoune::Context&, Kakoune::NormalParams)::{lambda(Kakoune::Key, Kakoune::Context&)#2}, Kakoune::StringView, Kakoune::select_object<(Kakoune::ObjectFlags)3, (Kakoune::SelectMode)0>(Kakoune::Context&, Kakoune::NormalParams)::{lambda(Kakoune::Key, Kakoune::Context&)#2})::{lambda(Kakoune::Key, Kakoune::Context&)#1}::operator()(Kakoune::Key, Kakoune::Context&) (this=0x555555f88358, key=..., context=...) at input_handler.hh:185
#13 0x0000555555be208d in std::_Function_handler<void (Kakoune::Key, Kakoune::Context&), Kakoune::on_next_key_with_autoinfo<Kakoune::select_object<(Kakoune::ObjectFlags)3, (Kakoune::SelectMode)0>(Kakoune::Context&, Kakoune::NormalParams)::{lambda(Kakoune::Key, Kakoune::Context&)#2}>(Kakoune::Context const&, Kakoune::KeymapMode, Kakoune::select_object<(Kakoune::ObjectFlags)3, (Kakoune::SelectMode)0>(Kakoune::Context&, Kakoune::NormalParams)::{lambda(Kakoune::Key, Kakoune::Context&)#2}, Kakoune::StringView, Kakoune::select_object<(Kakoune::ObjectFlags)3, (Kakoune::SelectMode)0>(Kakoune::Context&, Kakoune::NormalParams)::{lambda(Kakoune::Key, Kakoune::Context&)#2})::{lambda(Kakoune::Key, Kakoune::Context&)#1}>::_M_invoke(std::_Any_data const&, Kakoune::Key&&, Kakoune::Context&) (__functor=..., __args#0=..., __args#1=...) at /usr/include/c++/8.3.0/bits/std_function.h:297
#14 0x0000555555af8145 in std::function<void (Kakoune::Key, Kakoune::Context&)>::operator()(Kakoune::Key, Kakoune::Context&) const (this=0x555555f88358, __args#0=..., __args#1=...) at /usr/include/c++/8.3.0/bits/std_function.h:687
#15 0x0000555555aefcef in Kakoune::InputModes::NextKey::on_key (this=0x555555f88340, key=...) at input_handler.cc:1126
#16 0x0000555555ae66c3 in Kakoune::InputMode::handle_key (this=0x555555f88340, key=...) at input_handler.cc:32
#17 0x0000555555ae478d in Kakoune::InputHandler::<lambda(Kakoune::Key)>::operator()(Kakoune::Key) const (__closure=0x7fffffffcdd0, key=...) at input_handler.cc:1670
#18 0x0000555555ae4993 in Kakoune::InputHandler::handle_key (this=0x555555dfece8, key=...) at input_handler.cc:1682
#19 0x000055555599dc84 in Kakoune::Client::process_pending_inputs (this=0x555555dfec70) at client.cc:98
#20 0x00005555559ad655 in Kakoune::ClientManager::process_pending_inputs (this=0x7fffffffd250) at client_manager.cc:103
#21 0x0000555555b446e0 in Kakoune::run_server (session="", server_init="", client_init="", init_coord=..., flags=Kakoune::ServerFlags::IgnoreKakrc, ui_type=Kakoune::UIType::NCurses, debug_flags=Kakoune::DebugFlags::None, files=ArrayView<Kakoune::StringView>) at main.cc:773
#22 0x0000555555b489c4 in main (argc=2, argv=0x7fffffffe6c8) at main.cc:1120
```
