### ISSUE TITLE
Issues to the latest suspend commit `cb26478`

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3069]
### Steps 

In Tmux, open buffers that have highlighting in two separate clients, then suspend/resume the main one.

I reckon this is caused by cb26478.

### Outcome 

The colors are randomly broken. The secondary client is now suspended as well.

Main client on the left:
![](https://files.catbox.moe/1b4ygb.png)

### Expected 

Colors remain correct, other clients within the editing session remain usable even when the main one is suspended.

Reopens #3061.

**Comment by lenormf** [comment]
We should probably revert the commit for now, then come up with a patch that actually works.

**Comment by lenormf** [comment]
The issue still occurs, even with `1de038a`.

When Git starts the editor to write a commit message and I create a new client, I can ^Z the original client back to the shell (`Kakoune forked server to background (99367), for session '99299'`), but not `fg` back into the editor any more (it's like I'm resuming the Git process, but not the Kakoune one).

The second client remains unusable until the Git process is resumed.

**Comment by mawww** [comment]
I suspect the issue here is that we have a different codepath for suspending if we fork a server, and that codepath does not suspend the process group. Can you check if changing `main.cc:611` to `kill(0, SIGTSTP)` instead of `raise(SIGTSTP)` fixes the issue ?

**Comment by lenormf** [comment]
Unfortunately it didn't have anything effect.

**Comment by lenormf** [comment]
Log from IRC, after testing the patch:

> ironzorg | with a single client, it works as expected; if I got another one open, ^Z on the first client closes both the client *and* the shell
>ironzorg | so when I quit the second client after that, the Tmux window closes up as well since no new shells are spawned with the second client

In the Kitty multiplexer, it works fine. In Tmux I get the above side effects.

**Comment by mawww** [comment]
cannot reproduce that here, can you give me the exact repro steps (my understanding is that the initial issue only happened when you were running from say `git commit`)

**Comment by lenormf** [comment]
I've recorded [a screencast](https://files.catbox.moe/5v3643.mkv).

**Comment by mawww** [comment]
Followed the screencast, cannot reproduce

**Comment by lenormf** [comment]
After running the client in GDB, it looks like it gets several signals:

```
# Hit ^Z in the original client
Program received signal SIGTSTP, Stopped (user).
#0  0x00007fea6165122b in kill () from /usr/lib/libc.so.6
#1  0x000055ff89f08c79 in Kakoune::NCursesUI::get_next_key() ()

# continue
Program received signal SIGTSTP, Stopped (user).
#0  0x00007fea61650f25 in raise () from /usr/lib/libc.so.6
#1  0x000055ff89ef44fb in Kakoune::run_client(Kakoune::StringView, Kakoune::StringView, Kakoune::StringView, Kakoune::Optional<Kakoune::BufferCoord>, Kakoune::UIType, bool) ()

# continue
Program received signal SIGHUP, Hangup.
#0  0x000055ff89f09ca0 in ?? ()
#1  <signal handler called>
#2  0x00007fea61650f25 in raise () from /usr/lib/libc.so.6
#3  0x000055ff89ef44fb in Kakoune::run_client(Kakoune::StringView, Kakoune::StringView, Kakoune::StringView, Kakoune::Optional<Kakoune::BufferCoord>, Kakoune::UIType, bool) ()

# continue
Program received signal SIGCONT, Continued.
#0  0x000055f6a1c37cc0 in ?? ()
#1  <signal handler called>
#2  0x000055f6a1c39ca0 in ?? ()
#3  <signal handler called>
#4  0x00007fd8a0d90f25 in raise () from /usr/lib/libc.so.6
#5  0x000055f6a1c244fb in Kakoune::run_client(Kakoune::StringView, Kakoune::StringView, Kakoune::StringView, Kakoune::Optional<Kakoune::BufferCoord>, Kakoune::UIType, bool) ()

# continue
Program received signal SIGTSTP, Stopped (user).
#0  0x00007fd8a0d90f25 in raise () from /usr/lib/libc.so.6
#1  0x000055f6a1c39b98 in Kakoune::NCursesUI::suspend() ()
#2  <signal handler called>
#3  0x00007fd8a0d90f25 in raise () from /usr/lib/libc.so.6
#4  0x000055f6a1c244fb in Kakoune::run_client(Kakoune::StringView, Kakoune::StringView, Kakoune::StringView, Kakoune::Optional<Kakoune::BufferCoord>, Kakoune::UIType, bool) ()

Inferior 1 (process 637154) exited with code 0377
```

I've also seen SIGTTIN at some point in the chain of `continue`s, but couldn't get a reproducer.

**Comment by mawww** [comment]
Which process am I seeing here, is that only the original client+server process, or also the second client ?

In any case, that SIGHUP seems quite strange, and would make kakoune quit. I think finding what triggers that SIGHUP is going to solve the issue.

**Comment by lenormf** [comment]
It's the "original client", the one that is spawned by Git.

I'll try to repeat the experiment with a debug binary, if that helps.

**Comment by lenormf** [comment]
```
# Hit ^Z in the original client
Program received signal SIGTSTP, Stopped (user).
#0  0x00007feeed08122b in kill () from /usr/lib/libc.so.6
#1  0x0000558cb90586e1 in Kakoune::NCursesUI::<lambda(unsigned char)>::operator()(unsigned char) const (__closure=0x7ffce94930f0, c=26 '\032') at ncurses_ui.cc:605
#2  0x0000558cb90599b2 in Kakoune::NCursesUI::get_next_key (this=0x558cba17d080) at ncurses_ui.cc:761
#3  0x0000558cb9056066 in Kakoune::NCursesUI::<lambda(Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode)>::operator()(Kakoune::FDWatcher &, Kakoune::FdEvents, Kakoune::EventMode) const (__closure=0x558cba17d258) at ncurses_ui.cc:334
#4  0x0000558cb90621a1 in std::_Function_handler<void(Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode), Kakoune::NCursesUI::NCursesUI()::<lambda(Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode)> >::_M_invoke(const std::_Any_data &, Kakoune::FDWatcher &, Kakoune::FdEvents &&, Kakoune::EventMode &&) (__functor=..., __args#0=..., __args#1=@0x7ffce94931ec: Kakoune::FdEvents::Read, __args#2=@0x7ffce94931e8: Kakoune::EventMode::Normal) at /usr/include/c++/9.2.0/bits/std_function.h:300
#5  0x0000558cb8f47038 in std::function<void (Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode)>::operator()(Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode) const (this=0x558cba17d258, __args#0=..., __args#1=Kakoune::FdEvents::Read, __args#2=Kakoune::EventMode::Normal) at /usr/include/c++/9.2.0/bits/std_function.h:690
#6  0x0000558cb8f457ea in Kakoune::FDWatcher::run (this=0x558cba17d250, events=Kakoune::FdEvents::Read, mode=Kakoune::EventMode::Normal) at event_manager.cc:24
#7  0x0000558cb8f46496 in Kakoune::EventManager::handle_next_events (this=0x7ffce94939a0, mode=Kakoune::EventMode::Normal, sigmask=0x0, block=true) at event_manager.cc:136
#8  0x0000558cb90227bb in Kakoune::run_server (session="", server_init="", client_init="", init_coord=..., flags=Kakoune::ServerFlags::None, ui_type=Kakoune::UIType::NCurses, debug_flags=Kakoune::DebugFlags::None, files=ArrayView<Kakoune::StringView> = {...}) at main.cc:793
#9  0x0000558cb9026b77 in main (argc=2, argv=0x7ffce9494ba8) at main.cc:1136
```

```
# continue
Program received signal SIGTSTP, Stopped (user).
#0  0x00007feeed080f25 in raise () from /usr/lib/libc.so.6
#1  0x0000558cb9021704 in Kakoune::run_client (session="40650", name="client0", client_init="try %^buffer '/tmp/t/.git/COMMIT_EDITMSG'; select '1.1,1.1'^; echo converted to client only mode", init_coord=..., ui_type=Kakoune::UIType::NCurses, suspend=true) at main.cc:622
#2  0x0000558cb902704a in main (argc=2, argv=0x7ffce9494ba8) at main.cc:1140
```

```
# continue
Program received signal SIGHUP, Hangup.
#0  Kakoune::NCursesUI::<lambda(int)>::_FUN(int) () at ncurses_ui.cc:354
#1  <signal handler called>
#2  0x00007feeed080f25 in raise () from /usr/lib/libc.so.6
#3  0x0000558cb9021704 in Kakoune::run_client (session="40650", name="client0", client_init="try %^buffer '/tmp/t/.git/COMMIT_EDITMSG'; select '1.1,1.1'^; echo converted to client only mode", init_coord=..., ui_type=Kakoune::UIType::NCurses, suspend=true) at main.cc:622
#4  0x0000558cb902704a in main (argc=2, argv=0x7ffce9494ba8) at main.cc:1140
```

```
# continue
Program received signal SIGCONT, Continued.
#0  Kakoune::signal_handler<&Kakoune::sighup_raised> () at ncurses_ui.cc:321
#1  <signal handler called>
#2  Kakoune::NCursesUI::<lambda(int)>::_FUN(int) () at ncurses_ui.cc:354
#3  <signal handler called>
#4  0x00007feeed080f25 in raise () from /usr/lib/libc.so.6
#5  0x0000558cb9021704 in Kakoune::run_client (session="40650", name="client0", client_init="try %^buffer '/tmp/t/.git/COMMIT_EDITMSG'; select '1.1,1.1'^; echo converted to client only mode", init_coord=..., ui_type=Kakoune::UIType::NCurses, suspend=true) at main.cc:622
#6  0x0000558cb902704a in main (argc=2, argv=0x7ffce9494ba8) at main.cc:1140
```

```
# continue
Program received signal SIGTSTP, Stopped (user).
#0  0x00007feeed080f25 in raise () from /usr/lib/libc.so.6
#1  0x0000558cb9056878 in Kakoune::NCursesUI::suspend (this=0x558cba171030) at ncurses_ui.cc:386
#2  0x0000558cb9056110 in Kakoune::NCursesUI::<lambda(int)>::operator()(int) const (__closure=0x0) at ncurses_ui.cc:354
#3  0x0000558cb905612d in Kakoune::NCursesUI::<lambda(int)>::_FUN(int) () at ncurses_ui.cc:354
#4  <signal handler called>
#5  0x00007feeed080f25 in raise () from /usr/lib/libc.so.6
#6  0x0000558cb9021704 in Kakoune::run_client (session="40650", name="client0", client_init="try %^buffer '/tmp/t/.git/COMMIT_EDITMSG'; select '1.1,1.1'^; echo converted to client only mode", init_coord=..., ui_type=Kakoune::UIType::NCurses, suspend=true) at main.cc:622
#7  0x0000558cb902704a in main (argc=2, argv=0x7ffce9494ba8) at main.cc:1140
```

```
# continue
[Inferior 1 (process 40650) exited with code 0377]
```

HTH.

**Comment by lenormf** [comment]
Can't reproduce any more.
