### ISSUE TITLE
builtin-terminal-ui: SEGV

### ISSUE THREAD

**Issue by eraserhd** [mawww/kakoune#3414]
### Steps

Editing a file with linting set up to refresh on NormalIdle, I get a client SEGV.  I can start a new client, and as soon as I use `:buffer` to select the file, the client SEGVs again.

Lines 1-103 are visible on the screen, terminal options are: `terminal_assistant=none terminal_status_on_top=true terminal_set_title=false`

Line 102 contains _two_ info boxes from linting, and displaying the second box seems to be the problem.

![segv](https://user-images.githubusercontent.com/147284/76887622-eebd1000-6858-11ea-8003-7a8375982ef1.png)

### Outcome/Stacktrace

```
#0  0x000000000087a12a in Kakoune::String::Data::is_long (this=0x0) at string.hh:191
#1  0x000000000087a18c in Kakoune::String::Data::data (this=0x0) at string.hh:195
#2  0x0000000000967b8c in Kakoune::String::data (this=0x0) at string.hh:131
#3  Kakoune::StringOps<Kakoune::String, char>::end (this=0x0) at string.hh:42
#4  Kakoune::StringOps<Kakoune::String, char>::column_length (this=0x0) at string.hh:65
#5  0x0000000000b63144 in Kakoune::TerminalUI::Window::Line::resize (this=0x165c8c0, width=142) at terminal_ui.cc:71
#6  0x0000000000b533f5 in Kakoune::TerminalUI::Window::blit (this=0x165b000, target=...) at terminal_ui.cc:130
#7  0x0000000000b54d3b in Kakoune::TerminalUI::redraw (this=0x165aec0, force=false) at terminal_ui.cc:367
#8  0x0000000000b54f86 in Kakoune::TerminalUI::refresh (this=0x165aec0, force=false) at terminal_ui.cc:386
#9  0x0000000000b17ab2 in Kakoune::RemoteClient::<lambda(Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode)>::operator()(Kakoune::FDWatcher &, Kakoune::FdEvents, Kakoune::EventMode) (__closure=0x166d680, watcher=..., events=Kakoune::FdEvents::Read) at remote.cc:681
#10 0x0000000000b19192 in std::_Function_handler<void(Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode), Kakoune::RemoteClient::RemoteClient(Kakoune::StringView, Kakoune::StringView, std::unique_ptr<Kakoune::UserInterface>&&, int, const EnvVarMap&, Kakoune::StringView, Kakoune::Optional<Kakoune::BufferCoord>)::<lambda(Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode)> >::_M_invoke(const std::_Any_data &, Kakoune::FDWatcher &, Kakoune::FdEvents &&, Kakoune::EventMode &&) (__functor=..., __args#0=...,
    __args#1=@0x7ffd3894488c: Kakoune::FdEvents::Read, __args#2=@0x7ffd38944888: Kakoune::EventMode::Normal)
    at /nix/store/gh9a48qcwzw588vy4w72w93kad0mhhi8-gcc-9.2.0/include/c++/9.2.0/bits/std_function.h:300
#11 0x000000000096be4c in std::function<void (Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode)>::operator()(Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode) const (this=0x166c438, __args#0=..., __args#1=Kakoune::FdEvents::Read,
    __args#2=Kakoune::EventMode::Normal) at /nix/store/gh9a48qcwzw588vy4w72w93kad0mhhi8-gcc-9.2.0/include/c++/9.2.0/bits/std_function.h:690
#12 0x000000000096a8dc in Kakoune::FDWatcher::run (this=0x166c430, events=Kakoune::FdEvents::Read, mode=Kakoune::EventMode::Normal)
    at event_manager.cc:24
#13 0x000000000096b49b in Kakoune::EventManager::handle_next_events (this=0x7ffd38944ce0, mode=Kakoune::EventMode::Normal, sigmask=0x0,
    block=true) at event_manager.cc:136
#14 0x0000000000a3bf4d in Kakoune::run_client (session="kakoune", name="", client_init="", init_coord=...,
    ui_type=Kakoune::UIType::Terminal, suspend=false) at main.cc:670
#15 0x0000000000a40b72 in main (argc=3, argv=0x7ffd389462a8) at main.cc:1170
```

In stack frame 5, (terminal_ui.cc:71), `it` is not dereferencable, and atoms looks garbage (`$14 = std::vector of length 2, capacity 57872138270461338 = {Cannot access memory at address 0x0
`)

In stack frame 6 (terminal_ui.cc:130): target.lines.size() = 104, pos.line = 103, lines.size() = 2, and:

```
(gdb) ins lines[0]
$21 = {atoms = std::vector of length 1, capacity 1 = {{text = "error: doseq binding vector requires even number of forms(col 13)", face = {
        fg = Kakoune::Color::RGB #bfc7d5, bg = Kakoune::Color::RGB #3e4452, attributes = Kakoune::Attribute::Normal}}}}
(gdb) ins lines[1]
$22 = {atoms = std::vector of length 1, capacity 1 = {{text = "warning: unused binding query(col 22)                            ", face = {
        fg = Kakoune::Color::RGB #bfc7d5, bg = Kakoune::Color::RGB #3e4452, attributes = Kakoune::Attribute::Normal}}}}
```

This patch prevents the crash:
```
diff --git a/src/terminal_ui.cc b/src/terminal_ui.cc
index a09e127c..10d386e7 100644
--- a/src/terminal_ui.cc
+++ b/src/terminal_ui.cc
@@ -131,6 +131,8 @@ void TerminalUI::Window::blit(Window& target)
         target_line->atoms.insert(target_line->erase_range(pos.column, size.column),
                                   line.atoms.begin(), line.atoms.end());
         ++target_line;
+        if (target_line == target.lines.end())
+            break;
     }
 }
```

I think this isn't right though, as it looks like there is some logic to place the info window either below or above the cursor that is off by one somewhere.

**Comment by eraserhd** [comment]
This was resolved.

**Comment by mawww** [comment]
I think github did not close it because the fix was not in the master branch yet, maybe there is a way to set the branch on which an issue applies ?
