### ISSUE TITLE
[BUG][CRASH] 

### ISSUE THREAD

**Issue by ifreund** [mawww/kakoune#4462]
### Version of Kakoune

v2021.11.08-30-g716f1f96

### Reproducer

This seems to be triggered by scrolling up through quick, repeated `<c-u>` presses while on a video call and sharing my screen. I've reproduced this crash 3 times now in this exact scenario but have failed to reproduce it otherwise.

### Outcome

Sorry for the screenshot of text, I wasn't able to copy paste from the window for whatever reason and the terminal was left in a non-functional state due to the crash so I couldn't copy-paste from there either.
![kak](https://user-images.githubusercontent.com/12723818/145222439-4fa72125-e183-478e-a921-ca45af9d3d63.png)

**Comment by ifreund** [comment]
`git log` shows that there have only been two commits that touch `src/command_manager.cc` since the working `v2021.11.08` tag:

```
$ git log v2021.11.08..HEAD src/command_manager.cc 
commit 28ac8adbfce32dc1c7de20de8bf7a2075ae3d4ef
Author: Maxime Coste <mawww@kakoune.org>
Date:   Thu Nov 25 12:23:21 2021 +1100

    Templatize parse_quoted to avoid utf8 decoding with ascii delimiter

commit 91550639bbbd20c92957b83abfbb3ec4c43b3ab4
Author: Maxime Coste <mawww@kakoune.org>
Date:   Sun Nov 21 11:15:08 2021 +1100

    More C++20 refactorings
    
    Use CTAD instead of make functions, requires instead of enable_if
```

This would probably be a good place to start looking for the regression.

**Comment by Screwtapello** [comment]
Can you reproduce when starting Kakoune with `kak -n`?

**Comment by Screwtapello** [comment]
Also, although you probably can't copy/paste in the traditional way from that dialog, if you select the text (by dragging across it in the usual way) you should be able to paste the text into GitHub by middle-clicking in the text-box (or three-finger-tapping if you're using a touchpad on Linux)

**Comment by ifreund** [comment]
> Can you reproduce when starting Kakoune with `kak -n`?

I haven't been able to yet, but I can't reproduce this reliably enough in general to be conclusive that my config has something to do with it.

**Comment by mawww** [comment]
From the callstack, it looks like Kakoune is executing a command received via `kak -p`, when you get that crash again can you keep that dialog open, and attach gdb to the given PID (the point of that dialog is that it suspends the crashed Kakoune process so it is still available for inspection). once in there, I expect going up the stack would lead you to remote.cc:819, can you print the 'command' variable and report that here ?

**Comment by mralusw** [comment]
There is also, of course, the option of uploading your `kakrc` and all related files, so that this can get reproduces; but that might mean possibly exposing private information.

**Comment by ifreund** [comment]
> There is also, of course, the option of uploading your `kakrc` and all related files, so that this can get reproduced; but that might mean possibly exposing private information.

It's been public since I started using kakoune https://github.com/ifreund/dotfiles/tree/trunk/config/kak

**Comment by sidkshatriya** [comment]
@ifreund I have another suggestion. Build and run kakoune with debug=yes i.e.

```sh
$ make install debug=yes
```

Now run kakoune like this for a few days. Hopefully you will be able to repeat this issue. And when you do, it's possible that you will fail in a kakoune assertion statement. When you run kakoune in release mode `kak_assert` statements are not executed. By the time the signal actually occurs it can be very difficult to figure out the root cause.

When you're able to repeat the error you'll get a stack trace that may be more actionable... Please post the stack trace here...

**Comment by mralusw** [comment]
> It's been public since I started using kakoune https://github.com/ifreund/dotfiles/tree/trunk/config/kak

Something is missing:
```
git clone https://github.com/ifreund/dotfiles/ /tmp/ifr
KAKOUNE_CONFIG_DIR=/tmp/ifr/config/kak kak
```

debug buffer:

```
/tmp/ifr/config/kak/kakrc:33:1: 'set-option': option not found: 'grepcmd'. Use declare-option first
/opt/kak-v2021.11.08/share/kak/kakrc:29:1: 'evaluate-commands': 8:1: 'source': 33:1: 'set-option': option not found: 'grepcmd'. Use declare-
error while parsing kakrc:
    1:1: 'source': 29:1: 'evaluate-commands': 8:1: 'source': 33:1: 'set-option': option not found: 'grepcmd'. Use declare-option first
Error: nothing left to undo

```

**Comment by ifreund** [comment]
@mralusw You probably don't have your global kakoune autoload directory in the same place I do, see https://github.com/ifreund/dotfiles/blob/trunk/config/kak/autoload/default

**Comment by mralusw** [comment]
I am not a Kakoune developer, and my only personal investment here is ,basically, to see `kak` be as robust as `vim`.

I see that you use a symlink, However, I'm not sure how this would work with cloning into a separate CONFIG dir.

**Comment by ifreund** [comment]
@mralusw to use my config you would need to modify that symlink to point to the kakoune install's autoload directory you wish to use for testing. Perhaps this is better figured out over IRC, i'm `ifreund` in the `#kakoune` channel on libera.chat.

**Comment by ifreund** [comment]
@mawww finally managed to reproduce it, seems to be entirely unrelated to the scrolling with <c-u> and instead related to `kak-lsp`/`zls` (a language server for Zig). 

Here's the `command` variable at `remote.cc:819`:
```
(gdb) bt
#0  0x00007f74803f63e6 in __GI___wait4 (pid=28083, stat_loc=stat_loc@entry=0x7fff819e2328, options=options@entry=0, usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
#1  0x00007f74803f63a7 in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc@entry=0x7fff819e2328, options=options@entry=0) at waitpid.c:38
#2  0x00007f7480374c0f in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:172
#3  0x0000000000492454 in Kakoune::notify_fatal_error (msg=...) at assert.cc:35
#4  0x00000000005879ad in Kakoune::signal_handler (signal=11) at main.cc:1029
#5  <signal handler called>
#6  0x00000000004b3b51 in Kakoune::(anonymous namespace)::skip_blanks_and_comments (state=...) at command_manager.cc:225
#7  Kakoune::CommandParser::read_token (this=this@entry=0x7fff819e2fa8, throw_on_unterminated=true) at command_manager.cc:398
#8  0x00000000004b2c95 in Kakoune::CommandManager::execute (this=0x7fff819e3750, command_line=..., context=..., shell_context=...) at command_manager.cc:530
#9  0x0000000000612dee in Kakoune::Server::Accepter::handle_available_input (this=0x1a50980, mode=Kakoune::EventMode::Normal) at remote.cc:819
#10 0x000000000050c55d in std::function<void (Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode)>::operator()(Kakoune::FDWatcher&, Kakoune::FdEvents, Kakoune::EventMode) const (this=0x7fff819e2fb8, __args=Kakoune::EventMode::Normal, __args=Kakoune::EventMode::Normal, __args=Kakoune::EventMode::Normal)
    at /bin/../lib64/gcc/x86_64-unknown-linux-gnu/10.2/../../../../include/c++/10.2/bits/std_function.h:622
#11 Kakoune::FDWatcher::run (this=0x7fff819e2fa8, events=<optimized out>, mode=Kakoune::EventMode::Normal) at event_manager.cc:28
#12 Kakoune::EventManager::handle_next_events (this=0x7fff819e39b0, mode=<optimized out>, sigmask=<optimized out>, block=<optimized out>) at event_manager.cc:143
#13 0x0000000000585632 in Kakoune::run_server (session=..., server_init=..., client_init=..., init_coord=..., flags=Kakoune::ServerFlags::StartupInfo, ui_type=Kakoune::UIType::Terminal, debug_flags=Kakoune::DebugFlags::None, files=...) at main.cc:879
#14 0x00000000005892d6 in main (argc=<optimized out>, argv=<optimized out>) at main.cc:1225
(gdb) f 8
#8  0x00000000004b2c95 in Kakoune::CommandManager::execute (this=0x7fff819e3750, command_line=..., context=..., shell_context=...)
    at command_manager.cc:530
530	       Optional<Token> token = parser.read_token(true);
(gdb) f 9
#9  0x0000000000612dee in Kakoune::Server::Accepter::handle_available_input (this=0x1a50980, mode=Kakoune::EventMode::Normal)
    at remote.cc:819
819	                   CommandManager::instance().execute(command, context);
(gdb) p command
$1 = {<Kakoune::StringOps<Kakoune::String, char>> = {<No data fields>}, static ms_empty = 
    {<Kakoune::StringOps<Kakoune::String, char>> = {<No data fields>}, static ms_empty = <same as static member of an already seen type>, 
    static option_type_name = <optimized out>, m_data = {u = {l = {static max_capacity = 72057594037927936, ptr = 0x0, size = 0, 
          capacity = 72057594037927936}, s = {static capacity = 22, string = '\000' <repeats 22 times>, size = 1 '\001'}}}}, 
  static option_type_name = <optimized out>, m_data = {u = {l = {static max_capacity = 72057594037927936, 
        ptr = 0x1aea260 "eval -client client0 'eval -buffer ''/home/ifreund/projects/zig-wlroots/src/types/pointer.zig'' ''set buffer lsp_semantic_tokens 1 1.7,1.9|module 6.11,6.20|type 13.11,13.25|type 18.11,18.17|type 19.15"..., size = 2013, capacity = 2014}, s = {
        static capacity = 22, string = "`\242\256\001\000\000\000\000\335\a\000\000\000\000\000\000\336\a\000\000\000\000", 
        size = 0 '\000'}}}}
(gdb) 
```
I can keep the gdb session open until this evening if you'd like me to poke at anything else in the stack trace.
