### ISSUE TITLE
[BUG][CRASH] DisplayLine::split() assert failed "it->begin() < pos" at display_buffer.cc:87

### ISSUE THREAD

**Issue by krobelus** [mawww/kakoune#4753]
### Version of Kakoune

latest master (24d6072353f7c7e7cac84b4eb085036a8c852f96) plus some patches that should be unrelated

### Reproducer

none, I was editing a rust file in insert mode and use `<c-r>"` when it crashed

### Outcome

I still have gdb attached so I can dig further

```
(gdb) bt
#0  0x00007f009faeadd7 in wait4 () from /usr/lib/libc.so.6
#1  0x00007f009fa6208b in ?? () from /usr/lib/libc.so.6
#2  0x0000561d1045a8fc in Kakoune::notify_fatal_error (msg=...) at assert.cc:36
#3  0x0000561d1045ab6b in Kakoune::on_assert_failed (message=0x561d108027e8 "assert failed \"it->begin() < pos\" at display_buffer.cc:87") at assert.cc:51
#4  0x0000561d1056e808 in Kakoune::DisplayLine::split (this=0x561d11ea5cd0, 
          it={<Kakoune::UseMemoryDomain<(Kakoune::MemoryDomain)8>> = {<No data fields>}, face = {fg = {{color = Kakoune::Color::Black, a = 1 '\001'}, r = 0 '\000', g = 0 '\000', b = 0 '\000'}, bg = {{color = Kakoune::Color::Default, a = 0 '\000'}, r = 0 '\000', g = 0 '\000', b = 0 '\000'}, attributes = Kakoune::Attribute::Normal, underline = {{color = Kakoune::Color::Default, a = 0 '\000'}, r = 0 '\000', g = 0 '\000', b = 0 '\000'}}, m_type = Kakoune::DisplayAtom::Range, m_buffer = 0x561d11c89c60, m_range = {begin = {<Kakoune::LineAndColumn<Kakoune::BufferCoord, Kakoune::LineCount, Kakoune::ByteCount>> = {line = {<Kakoune::StronglyTypedNumber<Kakoune::LineCount, int>> = {m_value = 56}, <No data fields>}, column = {<Kakoune::StronglyTypedNumber<Kakoune::ByteCount, int>> = {m_value = 100}, <No data fields>}}, <No data fields>}, end = {<Kakoune::LineAndColumn<Kakoune::BufferCoord, Kakoune::LineCount, Kakoune::ByteCount>> = {line = {<Kakoune::StronglyTypedNumber<Kakoune::LineCount, int>> = {m_value = 56}, <No data fields>}, column = {<Kakoune::StronglyTypedNumber<Kakoune::ByteCount, int>> = {m_value = 105}, <No data fields>}}, <No data fields>}}, m_text = {<Kakoune::StringOps<Kakoune::String, char>> = {<No data fields>}, m_data = {u = {l = {static max_capacity = 72057594037927936, ptr = 0x7fffe0a90000 "@", size = 140736962569876, capacity = 72198331000497840}, s = {static capacity = 22, string = "\000\000\251\340\377\177\000\000\224&\251\340\377\177\000\000\260&\251\340\377\177", size = 1 '\001'}}}}}, pos=...) at display_buffer.cc:87
#5  0x0000561d1056ee44 in Kakoune::DisplayLine::split (this=0x561d11ea5cd0, 
          it={<Kakoune::UseMemoryDomain<(Kakoune::MemoryDomain)8>> = {<No data fields>}, face = {fg = {{color = Kakoune::Color::Black, a = 1 '\001'}, r = 0 '\000', g = 0 '\000', b = 0 '\000'}, bg = {{color = Kakoune::Color::Default, a = 0 '\000'}, r = 0 '\000', g = 0 '\000', b = 0 '\000'}, attributes = Kakoune::Attribute::Normal, underline = {{color = Kakoune::Color::Default, a = 0 '\000'}, r = 0 '\000', g = 0 '\000', b = 0 '\000'}}, m_type = Kakoune::DisplayAtom::Range, m_buffer = 0x561d11c89c60, m_range = {begin = {<Kakoune::LineAndColumn<Kakoune::BufferCoord, Kakoune::LineCount, Kakoune::ByteCount>> = {line = {<Kakoune::StronglyTypedNumber<Kakoune::LineCount, int>> = {m_value = 56}, <No data fields>}, column = {<Kakoune::StronglyTypedNumber<Kakoune::ByteCount, int>> = {m_value = 100}, <No data fields>}}, <No data fields>}, end = {<Kakoune::LineAndColumn<Kakoune::BufferCoord, Kakoune::LineCount, Kakoune::ByteCount>> = {line = {<Kakoune::StronglyTypedNumber<Kakoune::LineCount, int>> = {m_value = 56}, <No data fields>}, column = {<Kakoune::StronglyTypedNumber<Kakoune::ByteCount, int>> = {m_value = 105}, <No data fields>}}, <No data fields>}}, m_text = {<Kakoune::StringOps<Kakoune::String, char>> = {<No data fields>}, m_data = {u = {l = {static max_capacity = 72057594037927936, ptr = 0x7fffe0a90000 "@", size = 140736962569876, capacity = 72198331000497840}, s = {static capacity = 22, string = "\000\000\251\340\377\177\000\000\224&\251\340\377\177\000\000\260&\251\340\377\177", size = 1 '\001'}}}}}, count=...) at display_buffer.cc:111
#6  0x0000561d105a763c in operator() (__closure=0x561d11c5d2c0, context=..., display_buffer=...) at highlighters.cc:658
#7  0x0000561d105acdcc in SimpleHighlighter::do_highlight (this=0x561d11c5d2b0, context=..., display_buffer=..., range=...) at highlighters.cc:42
#8  0x0000561d1059eb02 in Kakoune::Highlighter::highlight (this=0x561d11c5d2b0, context=..., display_buffer=..., range=...) at highlighter.cc:12
#9  0x0000561d1059f045 in Kakoune::HighlighterGroup::do_highlight (this=0x561d11aa65f8, context=..., display_buffer=..., range=...) at highlighter_group.cc:12
#10 0x0000561d1059eb02 in Kakoune::Highlighter::highlight (this=0x561d11aa65f8, context=..., display_buffer=..., range=...) at highlighter.cc:12
#11 0x0000561d105a0116 in Kakoune::Highlighters::highlight (this=0x561d11aa65e8, context=..., display_buffer=..., range=...) at highlighter_group.cc:89
#12 0x0000561d105a00b5 in Kakoune::Highlighters::highlight (this=0x561d11aa6688, context=..., display_buffer=..., range=...) at highlighter_group.cc:88
#13 0x0000561d107e87bb in Kakoune::Window::update_display_buffer (this=0x561d11aa60b0, context=...) at window.cc:159
#14 0x0000561d104917dd in Kakoune::Client::redraw_ifn (this=0x561d11c68050) at client.cc:232
#15 0x0000561d104a1daf in Kakoune::ClientManager::redraw_clients (this=0x7fffe0a93350) at client_manager.cc:227
#16 0x0000561d106727f8 in Kakoune::run_server (session=..., server_init=..., client_init=..., init_coord=..., flags=Kakoune::ServerFlags::StartupInfo, 
    ui_type=Kakoune::UIType::Terminal, debug_flags=Kakoune::DebugFlags::None, files=...) at main.cc:886
#17 0x0000561d1067727a in main (argc=1, argv=0x7fffe0a94788) at main.cc:1241
```

**Comment by krobelus** [comment]
easy steps to reproduce:

    echo 🔎 | kak -n -e 'add-highlighter global/ column 5 ,black; hook -once global NormalIdle .* %{exec ypp}'

perhaps related to this summer's column highlighter changes
