### ISSUE TITLE
Crash on `:` in normal mode

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#640]
Hi,

On commit b0d72eb, code compiled with the following CLI options:
```
g++ -D_FORTIFY_SOURCE=2 -I/usr/include/ncursesw -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -O3 -pedantic -std=gnu++11 -g -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF […]
```

Haven't had much time to test anything else or try to bisect the faulty commit, although I have a hunch that the error comes from the changes in 1d646c03.

Backtrace:
```
#0  0x000055555569c833 in Kakoune::CommandManager::complete_command_name(Kakoune::Context const&, Kakoune::StringView, bool) const ()
#1  0x000055555569d3f4 in Kakoune::CommandManager::complete(Kakoune::Context const&, Kakoune::CompletionFlags, Kakoune::StringView, Kakoune::ByteCount) ()
#2  0x000055555566da60 in ?? ()
#3  0x0000555555652eef in Kakoune::InputModes::Prompt::refresh_completions(Kakoune::CompletionFlags) ()
#4  0x0000555555647131 in Kakoune::InputHandler::prompt(Kakoune::StringView, Kakoune::String, Kakoune::Face, std::function<Kakoune::Completions (Kakoune::Context const&, Kakoune::CompletionFlags, Kakoune::StringView, Kakoune::ByteCount)>, std::function<void (Kakoune::StringView, Kakoune::PromptEvent, Kakoune::Context&)>) ()
#5  0x000055555566e783 in Kakoune::command(Kakoune::Context&, Kakoune::NormalParams) ()
#6  0x0000555555650441 in Kakoune::InputModes::Normal::on_key(Kakoune::Key) ()
#7  0x0000555555645c3b in Kakoune::InputHandler::handle_key(Kakoune::Key) ()
#8  0x00005555555eb2df in Kakoune::Client::handle_available_input(Kakoune::EventMode) ()
#9  0x000055555563aca8 in ?? ()
#10 0x0000555555656532 in Kakoune::EventManager::handle_next_events(Kakoune::EventMode, __sigset_t*) ()
#11 0x0000555555666f04 in run_server(Kakoune::StringView, Kakoune::StringView, bool, bool, UIType, Kakoune::ArrayView<Kakoune::StringView const>, Kakoune::ByteCoord) ()
#12 0x00005555555c0014 in main ()
```

**Comment by lenormf** [comment]
I came up with the following patch to work around the issue, until a fix is merged:
```
diff --git a/src/command_manager.cc b/src/command_manager.cc
index ff4b589..7230c56 100644
--- a/src/command_manager.cc
+++ b/src/command_manager.cc
@@ -516,7 +516,6 @@ Completions CommandManager::complete_command_name(const Context& context,
                                                   StringView query, bool with_aliases) const
 {
     auto commands = m_commands
-            | filter([](const CommandMap::value_type& cmd) { return not (cmd.second.flags & CommandFlags::Hidden); })
             | transform([](const CommandMap::value_type& cmd) { return StringView{cmd.first}; });
 
     if (not with_aliases)
```

**Comment by mawww** [comment]
should be fixed now.
